version: "3"

networks:
  backend:
    external: true

services:
  app:
    container_name: portainer-agent-prod-1
    deploy:
      mode: global
    image: "portainer/agent:latest"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    labels:
      - traefik.enable=true
      - traefik.tcp.routers.portainer-agent-prod-1.entrypoints=portainer-agent
      - traefik.tcp.routers.portainer-agent-prod-1.rule=HostSNI(`portainer-agent-prod-1.birthdayy.dev`)
      - traefik.tcp.routers.portainer-agent-prod-1.tls.certresolver=cloudfare
      - traefik.tcp.services.portainer-agent-prod-1.middlewares=portainer-agent-prod-1-middleware@file
      - traefik.tcp.services.portainer-agent-prod-1.loadbalancer.server.port=9001
    networks:
      - backend
    restart: always
