---
networks:
  frontend:
    external: true
volumes:
  dockge-data:
services:
  dockge:
    container_name: dockge-prod-1
    image: louislam/dockge:1.4.2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - dockge-data:/app/data
      - /home/swiizyy:/home/swiizyy
    environment:
      - DOCKGE_STACKS_DIR=/home/swiizyy
    labels:
      - traefik.enable=true
      - traefik.http.routers.dockge-prod-1-https.entrypoints=websecure
      - traefik.http.routers.dockge-prod-1-https.rule=Host(`dockge-prod-1.birthdayy.dev`)
      - traefik.http.routers.dockge-prod-1-https.tls=true
      - traefik.http.routers.dockge-prod-1-https.tls.certresolver=cloudflare
    networks:
      - frontend
    restart: unless-stopped
