---
networks:
  frontend:
    external: true
  backend:
    external: true
volumes:
  mariadb-data:
    external: true
services:
  mariadb:
    container_name: db-prod-1
    image: mariadb:11.0.3
    ports:
      - 3306:3306
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      - MARIADB_RANDOM_ROOT_PASSWORD=$MARIADB_RANDOM_ROOT_PASSWORD
    networks:
      - frontend
      - backend
    restart: unless-stopped
