global:
  checkNewVersion: false
  sendAnonymousUsage: false

log:
  level: ERROR

api:
  dashboard: true
  insecure: false
  debug: false

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: :443

certificatesResolvers:
  http:
    acme:
      email: "contact@birthdayy.xyz"
      storage: /etc/traefik/certs/http-acme.json
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
      keyType: EC256
      httpChallenge:
        entryPoint: web

serversTransport:
  insecureSkipVerify: true

providers:
  docker:
    exposedByDefault: false
    endpoint: "unix:///var/run/docker.sock"
    watch: true
    swarmMode: false
  file:
    directory: /etc/traefik/conf/
    watch: true
